### ISSUE TITLE
Samsung Note 5 Incompatible

### ISSUE THREAD

**Issue by mgorfer** [starryalley/Messages.png_Android#1]
I am using a Samsung Note 5 but I cannot install the App, because `This app is incompatible with your device.` Is there any plan to support it in the future? I would love to use your app in combination with my Fenix 6.

**Comment by starryalley** [comment]
It looks like Note 5 is still using android version 5. I'll see what I can do to make it support android 5. I hope it will be in near future.

**Comment by mgorfer** [comment]
No, the current Android version on the Note 5 is 7.0.

**Comment by starryalley** [comment]
Oh thanks. I've set
`
minSdkVersion 26
targetSdkVersion 28
`
So that means this only runs on Android >=8.0. 
I'll see if I can make it support Android 7.0 (API version 24)

**Comment by starryalley** [comment]
I've released 1.0.5 on google play which supports Android 7.0+. Please give it a test. Thanks.

**Comment by mgorfer** [comment]
Works great! Thank you for the fast support!
